import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Layout } from "@/components/layout/Layout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { UserPlus, Loader2 } from "lucide-react";
import { z } from "zod";

const kidSchema = z.object({
  full_name: z
    .string()
    .min(1, "Full name is required")
    .regex(/^[a-zA-Z\s]+$/, "Name should only contain letters"),
  standard: z
    .number({ invalid_type_error: "Standard must be a number" })
    .min(1, "Standard must be between 1 and 12")
    .max(12, "Standard must be between 1 and 12"),
  age: z
    .number({ invalid_type_error: "Age must be a number" })
    .min(1, "Age is required")
    .max(20, "Age must be less than 20"),
  school_name: z.string().min(1, "School name is required"),
  father_phone: z
    .string()
    .regex(/^\d{10}$/, "Father phone must be exactly 10 digits"),
  mother_phone: z
    .string()
    .regex(/^\d{10}$/, "Mother phone must be exactly 10 digits"),
  address: z.string().optional(),
});

type KidFormData = z.infer<typeof kidSchema>;

export default function RegisterKid() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [formData, setFormData] = useState({
    full_name: "",
    standard: "",
    age: "",
    school_name: "",
    father_phone: "",
    mother_phone: "",
    address: "",
  });

  const mutation = useMutation({
    mutationFn: async (data: KidFormData) => {
      // registration_id is auto-generated by database trigger
      const { error } = await supabase.from("kids").insert({
        full_name: data.full_name,
        standard: data.standard,
        age: data.age,
        school_name: data.school_name,
        father_phone: data.father_phone,
        mother_phone: data.mother_phone,
        address: data.address || null,
      } as any);
      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["kids"] });
      queryClient.invalidateQueries({ queryKey: ["kids-count"] });
      toast.success("Kid registered successfully!");
      navigate("/kids");
    },
    onError: (error: Error) => {
      toast.error(error.message || "Failed to register kid");
    },
  });

  const handleChange = (
    e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
    setErrors((prev) => ({ ...prev, [name]: "" }));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    const parsed = kidSchema.safeParse({
      ...formData,
      standard: formData.standard ? parseInt(formData.standard) : undefined,
      age: formData.age ? parseInt(formData.age) : undefined,
    });

    if (!parsed.success) {
      const fieldErrors: Record<string, string> = {};
      parsed.error.errors.forEach((err) => {
        if (err.path[0]) {
          fieldErrors[err.path[0] as string] = err.message;
        }
      });
      setErrors(fieldErrors);
      return;
    }

    mutation.mutate(parsed.data);
  };

  return (
    <Layout>
      <div className="max-w-2xl mx-auto animate-fade-in">
        <Card className="card-elevated">
          <CardHeader className="text-center">
            <div className="mx-auto w-16 h-16 rounded-2xl gradient-primary flex items-center justify-center mb-4 shadow-soft">
              <UserPlus className="h-8 w-8 text-primary-foreground" />
            </div>
            <CardTitle className="text-2xl font-heading">
              Register New Kid
            </CardTitle>
            <p className="text-muted-foreground">
              Fill in the details to register a new kid for Bal-Sabha
            </p>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-5">
              {/* Full Name */}
              <div className="space-y-2">
                <Label htmlFor="full_name">Full Name *</Label>
                <Input
                  id="full_name"
                  name="full_name"
                  value={formData.full_name}
                  onChange={handleChange}
                  placeholder="Enter full name"
                  className="input-styled"
                />
                {errors.full_name && (
                  <p className="text-sm text-destructive">{errors.full_name}</p>
                )}
              </div>

              {/* Standard & Age */}
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="standard">Standard (1-12) *</Label>
                  <Input
                    id="standard"
                    name="standard"
                    type="number"
                    min="1"
                    max="12"
                    value={formData.standard}
                    onChange={handleChange}
                    placeholder="e.g., 5"
                    className="input-styled"
                  />
                  {errors.standard && (
                    <p className="text-sm text-destructive">{errors.standard}</p>
                  )}
                </div>
                <div className="space-y-2">
                  <Label htmlFor="age">Age *</Label>
                  <Input
                    id="age"
                    name="age"
                    type="number"
                    min="1"
                    max="20"
                    value={formData.age}
                    onChange={handleChange}
                    placeholder="e.g., 10"
                    className="input-styled"
                  />
                  {errors.age && (
                    <p className="text-sm text-destructive">{errors.age}</p>
                  )}
                </div>
              </div>

              {/* School Name */}
              <div className="space-y-2">
                <Label htmlFor="school_name">School Name *</Label>
                <Input
                  id="school_name"
                  name="school_name"
                  value={formData.school_name}
                  onChange={handleChange}
                  placeholder="Enter school name"
                  className="input-styled"
                />
                {errors.school_name && (
                  <p className="text-sm text-destructive">{errors.school_name}</p>
                )}
              </div>

              {/* Phone Numbers */}
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="father_phone">Father's Phone *</Label>
                  <Input
                    id="father_phone"
                    name="father_phone"
                    value={formData.father_phone}
                    onChange={handleChange}
                    placeholder="10 digits"
                    maxLength={10}
                    className="input-styled"
                  />
                  {errors.father_phone && (
                    <p className="text-sm text-destructive">
                      {errors.father_phone}
                    </p>
                  )}
                </div>
                <div className="space-y-2">
                  <Label htmlFor="mother_phone">Mother's Phone *</Label>
                  <Input
                    id="mother_phone"
                    name="mother_phone"
                    value={formData.mother_phone}
                    onChange={handleChange}
                    placeholder="10 digits"
                    maxLength={10}
                    className="input-styled"
                  />
                  {errors.mother_phone && (
                    <p className="text-sm text-destructive">
                      {errors.mother_phone}
                    </p>
                  )}
                </div>
              </div>

              {/* Address */}
              <div className="space-y-2">
                <Label htmlFor="address">Address (Optional)</Label>
                <Textarea
                  id="address"
                  name="address"
                  value={formData.address}
                  onChange={handleChange}
                  placeholder="Enter address"
                  className="input-styled min-h-[80px] resize-none"
                />
              </div>

              {/* Submit */}
              <Button
                type="submit"
                disabled={mutation.isPending}
                className="w-full btn-primary"
              >
                {mutation.isPending ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Registering...
                  </>
                ) : (
                  <>
                    <UserPlus className="mr-2 h-4 w-4" />
                    Register Kid
                  </>
                )}
              </Button>
            </form>
          </CardContent>
        </Card>
      </div>
    </Layout>
  );
}
